---
swagger: "2.0"
info:
  version: 1.0.0
  title: Address path item
  description: This is a component file, used within the Uber API specification.

paths:
  /user:
    get:
      summary: User Profile
      description: The User Profile endpoint returns information about the Uber user that has authorized with the application.
      tags:
        - User
      responses:
        200:
          description: Profile information for a user
          schema:
            # Reference to a Schema Object described in 'definitions' section of uber_schemas.yaml
            $ref: "./uber_schemas.yaml#/definitions/Profile"
        default:
          # Defaults to an unexpected error response, defined in uber_responses.yaml.
          $ref: "./uber_responses.yaml#/responses/ErrorResponse"
