---
swagger: "2.0"
info:
  version: 1.0.0
  title: Address path item
  description: This is a component file, used within the Uber API specification.

paths:
  /history:
    get:
      summary: User Activity
      description: The User Activity endpoint returns data about a user's lifetime activity with Uber. The response will include pickup locations and times, dropoff locations and times, the distance of past requests, and information about which products were requested.<br><br>The history array in the response will have a maximum length based on the limit parameter. The response value count may exceed limit, therefore subsequent API requests may be necessary.
      parameters:
        - $ref: "./uber_parameters.yaml#/parameters/offset"
        - $ref: "./uber_parameters.yaml#/parameters/limit"
      tags:
        - User
      responses:
        200:
          description: History information for the given user
          schema:
            # Reference to a Schema Object described in 'definitions' section of uber_schemas.yaml
            $ref: "./uber_schemas.yaml#/definitions/Activities"
        default:
          # Defaults to an unexpected error response, defined in uber_responses.yaml.
          $ref: "./uber_responses.yaml#/responses/ErrorResponse"
