---
swagger: "2.0"
info:
  version: 1.0.0
  title: Uber Parameters

# This is a component file, used by the Uber API specification.
# The paths property is required, so we use curly braces to denote an empty object,
# meaning there are no path items defined in this file.
paths: {}

# The parameters section contains a set of named, reusable Parameter Objects.
# We refer to these using a $ref property, with a JSON Reference value that resolves
# to a Parameter Object defined here.
parameters:

  latitude:
    name: latitude
    in: query
    description: Latitude component of location.
    required: true
    type: number
    format: double

  longitude:
    name: longitude
    in: query
    description: Longitude component of location.
    required: true
    type: number
    format: double

  start_latitude:
    name: start_latitude
    in: query
    description: Latitude component of start location.
    required: true
    type: number
    format: double

  start_longitude:
    name: start_longitude
    in: query
    description: Longitude component of start location.
    required: true
    type: number
    format: double

  end_latitude:
    name: end_latitude
    in: query
    description: Latitude component of end location.
    required: true
    type: number
    format: double

  end_longitude:
    name: end_longitude
    in: query
    description: Longitude component of end location.
    required: true
    type: number
    format: double

  customer_uuid:
    name: customer_uuid
    in: query
    type: string
    format: uuid
    description: Unique customer identifier to be used for experience customization.

  product_id:
    name: product_id
    in: query
    type: string
    description: Unique identifier representing a specific product for a given latitude & longitude.

  offset:
    name: offset
    in: query
    type: integer
    format: int32
    description: Offset the list of returned results by this amount. Default is zero.

  limit:
    name: limit
    in: query
    type: integer
    format: int32
    description: Number of items to retrieve. Default is 5, maximum is 100.
