---
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: BeamUp API

paths:
  /products:
    # Operations are identified by an HTTP method.  
    get:
      summary: Product Types
      description: |
        The Products endpoint returns information about the BeamUp products offered at 
        a given location. The response includes the display name and other details 
        about each product, and lists the products in the proper display order.
      parameters:
        - $ref: "../components/beamup_parameters.yaml#/components/parameters/latitude"
        - $ref: "../components/beamup_parameters.yaml#/components/parameters/longitude"
      tags: 
        - Products
      responses:  
        200:
          description: An array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  # Reference to a Schema Object described in beamup_schemas.yaml
                  $ref: "../components/beamup_schemas.yaml#/components/schemas/Product"
        default:
          # Defaults to an unexpected error response, defined in beamup_responses.yaml.
          $ref: "../components/beamup_responses.yaml#/components/responses/ErrorResponse"
